const std = @import("std");

const DEFAULT_RAM_BASE: u64 = 0x80000000;

/// Resolve a `-D<name>=0x...` address option, or a default.
fn optAddr(b: *std.Build, name: []const u8, desc: []const u8, default: u64) u64 {
    if (b.option([]const u8, name, desc)) |s| {
        return std.fmt.parseInt(u64, s, 0) catch std.debug.panic("invalid -D{s}: {s}", .{ name, s });
    }
    return default;
}

/// Generate the FSBL linker script for a given run base (SRAM or flash).
fn fsblLinker(b: *std.Build, base: u64) std.Build.LazyPath {
    const text = b.fmt(
        \\/* Generated by build.zig. First-stage boot loader image. */
        \\ENTRY(_start)
        \\BASE = 0x{x};
        \\STACK = 0x4000; /* 16 KiB FSBL stack */
        \\SECTIONS
        \\{{
        \\    . = BASE;
        \\    .text : {{ KEEP(*(.text.boot)) *(.text .text.*) }}
        \\    . = ALIGN(8);
        \\    .rodata : {{ *(.rodata .rodata.* .srodata .srodata.*) }}
        \\    . = ALIGN(8);
        \\    .data : {{ PROVIDE(__global_pointer$ = . + 0x800); *(.data .data.* .sdata .sdata.*) }}
        \\    . = ALIGN(8);
        \\    .bss (NOLOAD) : {{ __bss_start = .; *(.bss .bss.* .sbss .sbss.* COMMON); . = ALIGN(8); __bss_end = .; }}
        \\    . = ALIGN(16);
        \\    . = . + STACK;
        \\    _stack_top = .;
        \\    /DISCARD/ : {{ *(.comment) *(.note .note.*) *(.eh_frame .eh_frame_hdr) *(.riscv.attributes) }}
        \\}}
        \\
    , .{base});
    return b.addWriteFiles().add("weir-fsbl.ld", text);
}

fn fdtBe32(d: []const u8, off: usize) u32 {
    return (@as(u32, d[off]) << 24) | (@as(u32, d[off + 1]) << 16) | (@as(u32, d[off + 2]) << 8) | d[off + 3];
}

/// Parse a flattened device tree and return the base address of its first
/// /memory node, so the firmware's link/layout base can come from the same SoC
/// description it boots with. Returns null on any malformed input.
fn fdtMemoryBase(d: []const u8) ?u64 {
    if (d.len < 40 or fdtBe32(d, 0) != 0xd00dfeed) return null;
    const total = fdtBe32(d, 4);
    const off_struct = fdtBe32(d, 8);
    const off_strings = fdtBe32(d, 12);
    if (total > d.len) return null;

    var off: usize = off_struct;
    var in_memory = false;
    while (off + 4 <= total) {
        const tok = fdtBe32(d, off);
        off += 4;
        switch (tok) {
            1 => { // FDT_BEGIN_NODE
                var l: usize = 0;
                while (off + l < d.len and d[off + l] != 0) l += 1;
                const name = d[off .. off + l];
                off = (off + l + 1 + 3) & ~@as(usize, 3);
                in_memory = std.mem.startsWith(u8, name, "memory") and
                    (name.len == 6 or name[6] == '@');
            },
            2 => in_memory = false, // FDT_END_NODE
            3 => { // FDT_PROP
                const len = fdtBe32(d, off);
                const nameoff = fdtBe32(d, off + 4);
                off += 8;
                const data_off = off;
                off = (off + len + 3) & ~@as(usize, 3);
                if (in_memory and len >= 8) {
                    var l: usize = 0;
                    while (d[off_strings + nameoff + l] != 0) l += 1;
                    if (std.mem.eql(u8, d[off_strings + nameoff .. off_strings + nameoff + l], "reg")) {
                        return (@as(u64, fdtBe32(d, data_off)) << 32) | fdtBe32(d, data_off + 4);
                    }
                }
            },
            4 => {}, // FDT_NOP
            else => break, // FDT_END or malformed
        }
    }
    return null;
}

/// Generate the firmware linker script for a given RAM base, so the link address
/// always matches mem.zig's ram_base.
fn linkerScript(b: *std.Build, ram_base: u64) std.Build.LazyPath {
    const text = b.fmt(
        \\/* Generated by build.zig. Firmware image layout for RISC-V.
        \\ * Loaded at the start of RAM in M-mode; the reset vector is _start. */
        \\ENTRY(_start)
        \\RAM_BASE = 0x{x};
        \\STACK_SIZE = 0x10000; /* 64 KiB per-hart (must stay 1 << 16; see start.zig) */
        \\MAX_HARTS = 8;
        \\SECTIONS
        \\{{
        \\    . = RAM_BASE;
        \\    .text : {{ KEEP(*(.text.boot)) *(.text .text.*) }}
        \\    . = ALIGN(8);
        \\    .rodata : {{ *(.rodata .rodata.* .srodata .srodata.*) }}
        \\    . = ALIGN(8);
        \\    __rodata_end = .; /* end of immutable image (code + rodata) for self-measurement */
        \\    .data : {{ PROVIDE(__global_pointer$ = . + 0x800); *(.data .data.* .sdata .sdata.*) }}
        \\    . = ALIGN(8);
        \\    .bss (NOLOAD) : {{ __bss_start = .; *(.bss .bss.* .sbss .sbss.* COMMON) . = ALIGN(8); __bss_end = .; }}
        \\    . = ALIGN(16);
        \\    _stacks_bottom = .;
        \\    . = . + STACK_SIZE * MAX_HARTS;
        \\    _stacks_top = .;
        \\    /DISCARD/ : {{ *(.comment) *(.note .note.*) *(.eh_frame .eh_frame_hdr) *(.riscv.attributes) }}
        \\}}
        \\
    , .{ram_base});
    return b.addWriteFiles().add("weir.ld", text);
}

pub fn build(b: *std.Build) void {
    const optimize = b.standardOptimizeOption(.{});

    // RISC-V firmware: freestanding, M-mode capable, soft-float (no F/D so we
    // never have to manage the FPU before handing off). medany code model (set
    // per-module below) is required because we link at 0x80000000.
    //
    // We accept only `-Dcpu` (the nixpkgs zig build hook passes -Dcpu=baseline),
    // never `-Dtarget`: the triple is always riscv64 freestanding. The cpu string
    // is parsed by the same stdlib path standardTargetOptions uses, against our
    // fixed triple, then the firmware's required features are pinned on top.
    const mcpu = b.option([]const u8, "cpu", "Target CPU features to add or subtract");
    var target_query = std.Build.parseTargetQuery(.{
        .arch_os_abi = "riscv64-freestanding-none",
        .cpu_features = mcpu,
    }) catch |err| switch (err) {
        // parseTargetQuery already printed the available CPUs/features to stderr.
        error.ParseFailed => std.process.exit(1),
    };
    target_query.cpu_features_add.addFeatureSet(std.Target.riscv.featureSet(&.{ .m, .a, .c }));
    target_query.cpu_features_sub.addFeatureSet(std.Target.riscv.featureSet(&.{ .d, .f }));
    const target = b.resolveTargetQuery(target_query);

    // Let the platform's ACPI/DT description be supplied at build time so Weir
    // can use a provided AML/DTB instead of generating tables purely.
    const aml_path = b.option([]const u8, "aml", "Path to an ACPI DSDT AML blob to embed as the firmware-provided DSDT");
    const dtb_lp = b.option(std.Build.LazyPath, "dtb", "Device tree to embed: SoC params (read at comptime) + runtime override");

    // The SoC device tree (-Ddtb) drives everything platform-specific: it is
    // embedded as `soc_dtb` (read at comptime by soc.zig) AND read here for the
    // firmware's link/layout base, so the two never disagree and there is no
    // -Dram-base to maintain. With no -Ddtb (the QEMU virt default) nothing is
    // embedded and the firmware falls back to the common addresses.
    var ram_base: u64 = DEFAULT_RAM_BASE;
    if (dtb_lp) |lp| {
        const cp = lp.getPath3(b, null);
        if (cp.root_dir.handle.readFileAlloc(b.graph.io, cp.sub_path, b.allocator, .limited(1 << 20))) |data| {
            if (fdtMemoryBase(data)) |base| ram_base = base;
        } else |_| {}
    }

    // An external S-mode payload (ELF) Weir loads and jumps to directly.
    const payload_path = b.option([]const u8, "payload", "Path to an S-mode ELF payload to embed and load");
    const has_payload = payload_path != null;

    // A real PE32+ EFI application (e.g. Limine's BOOTRISCV64.EFI) to embed and
    // load through the PE/COFF loader instead of the ELF path.
    const pe_app_path = b.option([]const u8, "pe-app", "Path to a real PE32+ EFI application to embed and load via the PE/COFF loader");

    // Read the EFI application off a virtio-blk disk at boot instead of from an
    // embedded blob. Attach the disk to QEMU with -drive/-device virtio-blk.
    const disk_boot = b.option(bool, "disk-boot", "Load the boot PE off a virtio-blk disk instead of an embedded blob") orelse false;

    // Full boot manager: find an ESP, mount FAT, honour BootOrder/Boot#### (or
    // the \EFI\BOOT\BOOTRISCV64.EFI fallback), and boot the referenced EFI app.
    const boot_manager = b.option(bool, "boot-manager", "Boot via the ESP boot manager (GPT + FAT + BootOrder)") orelse false;

    // An initramfs to hand the Linux kernel via the LoadFile2 protocol, so it
    // reaches a real userspace instead of panicking for lack of a root fs.
    const initrd_path = b.option([]const u8, "initrd", "Path to an initramfs (cpio.gz) to embed and serve via LoadFile2");

    const options = b.addOptions();
    options.addOption(bool, "has_aml", aml_path != null);
    options.addOption(bool, "has_dtb", dtb_lp != null);
    options.addOption(bool, "has_payload", has_payload);
    options.addOption(bool, "has_pe_app", pe_app_path != null);
    options.addOption(bool, "disk_boot", disk_boot);
    options.addOption(bool, "boot_manager", boot_manager);
    options.addOption(bool, "has_initrd", initrd_path != null);

    const mod = b.createModule(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
        .code_model = .medium,
    });
    mod.addOptions("build_options", options);
    // conduit: the shared Midstall HAL, and Weir's single Midstall dependency. It
    // backs Weir's peripheral access (UART, virtio-blk, SDHCI, Harbor, CLINT) and
    // its discovery, and re-exports dtree (comptime SoC-param reading in soc.zig)
    // and almanac (ACPI table building in acpi/*) so Weir never pulls those in
    // directly. conduit's build.zig wires its own transitive deps; we consume the
    // pre-built module for our target.
    const conduit_dep = b.dependency("conduit", .{ .target = target, .optimize = optimize });
    const conduit_mod = conduit_dep.module("conduit");
    // Shared SoC-parameters module: reads the embedded DT at comptime. Used by
    // both the firmware and the FSBL, so neither needs -D address options.
    const soc_mod = b.createModule(.{
        .root_source_file = b.path("src/soc.zig"),
        .target = target,
        .optimize = optimize,
        .code_model = .medium,
    });
    soc_mod.addImport("conduit", conduit_mod);
    const soc_opts = b.addOptions();
    soc_opts.addOption(bool, "has_dtb", dtb_lp != null);
    soc_mod.addOptions("build_options", soc_opts);
    if (dtb_lp) |lp| soc_mod.addAnonymousImport("soc_dtb", .{ .root_source_file = lp });

    mod.addImport("soc", soc_mod);
    mod.addImport("conduit", conduit_mod);
    if (dtb_lp) |lp| mod.addAnonymousImport("weir_dtb", .{ .root_source_file = lp });
    if (aml_path) |p| mod.addAnonymousImport("weir_aml", .{ .root_source_file = b.path(p) });
    // cwd_relative so an absolute path (e.g. a Nix store EFI binary) also works.
    if (pe_app_path) |p| mod.addAnonymousImport("weir_pe_app", .{ .root_source_file = .{ .cwd_relative = p } });
    if (initrd_path) |p| mod.addAnonymousImport("weir_initrd", .{ .root_source_file = .{ .cwd_relative = p } });

    if (payload_path) |p| {
        mod.addAnonymousImport("weir_payload", .{ .root_source_file = b.path(p) });
    }

    const exe = b.addExecutable(.{
        .name = "weir",
        .root_module = mod,
    });
    exe.entry = .{ .symbol_name = "_start" };
    exe.setLinkerScript(linkerScript(b, ram_base));
    b.installArtifact(exe);

    // Flat image for `-bios`.
    const bin = exe.addObjCopy(.{ .format = .bin });
    const install_bin = b.addInstallBinFile(bin.getOutput(), "weir.bin");
    b.getInstallStep().dependOn(&install_bin.step);

    // `zig build qemu` boots the firmware under QEMU's virt machine.
    const run = b.addSystemCommand(&.{
        "qemu-system-riscv64",
        "-machine",
        "virt",
        "-smp",
        "2",
        "-m",
        "128M",
        "-nographic",
        "-bios",
    });
    run.addFileArg(bin.getOutput());
    if (b.args) |args| run.addArgs(args);
    const qemu_step = b.step("qemu", "Boot Weir under qemu-system-riscv64 -machine virt");
    qemu_step.dependOn(&run.step);

    // First-stage boot loader: a separate tiny image that runs from SRAM/flash
    // at reset, brings up DRAM, and loads the main firmware into it. Hardware
    // addresses come from the SoC device tree (the shared soc module, comptime);
    // only the flash layout policy and link base are options. `zig build fsbl`.
    {
        const fsbl_base = optAddr(b, "fsbl-base", "FSBL link/run base (SRAM or flash)", 0x80000000);
        const fsbl_main_off = optAddr(b, "fsbl-main-offset", "main image offset within flash", 0x100000);
        const fsbl_main_max = optAddr(b, "fsbl-main-max", "max main image bytes to copy", 16 << 20);

        const fopts = b.addOptions();
        fopts.addOption(usize, "main_offset", @intCast(fsbl_main_off));
        fopts.addOption(usize, "main_max", @intCast(fsbl_main_max));

        const fmod = b.createModule(.{
            .root_source_file = b.path("src/fsbl/start.zig"),
            .target = target,
            .optimize = optimize,
            .code_model = .medium,
        });
        fmod.addOptions("fsbl_options", fopts);
        fmod.addImport("soc", soc_mod); // SoC addresses, comptime from the DT
        fmod.addImport("conduit", conduit_mod);
        // Share the UART driver with the main firmware (the FSBL module is rooted
        // under src/fsbl, so cross-tree files come in as named imports). uart.zig
        // is a thin adapter over conduit's ns16550a, so it needs conduit too.
        const fsbl_uart_mod = b.createModule(.{
            .root_source_file = b.path("src/console/uart.zig"),
            .target = target,
            .optimize = optimize,
            .code_model = .medium,
        });
        fsbl_uart_mod.addImport("conduit", conduit_mod);
        fmod.addImport("uart", fsbl_uart_mod);
        // Share the TPM2 command layer (which pulls in the TIS transport) and the
        // handoff record so the FSBL can measure main Weir into the TPM.
        const fsbl_tpm2_mod = b.createModule(.{
            .root_source_file = b.path("src/tpm/tpm2.zig"),
            .target = target,
            .optimize = optimize,
            .code_model = .medium,
        });
        fmod.addImport("tpm2", fsbl_tpm2_mod);
        const fsbl_handoff_mod = b.createModule(.{
            .root_source_file = b.path("src/boot_handoff.zig"),
            .target = target,
            .optimize = optimize,
            .code_model = .medium,
        });
        fmod.addImport("boot_handoff", fsbl_handoff_mod);

        const fexe = b.addExecutable(.{ .name = "weir-fsbl", .root_module = fmod });
        fexe.entry = .{ .symbol_name = "_start" };
        fexe.setLinkerScript(fsblLinker(b, fsbl_base));

        const fbin = fexe.addObjCopy(.{ .format = .bin });
        const finstall = b.addInstallBinFile(fbin.getOutput(), "weir-fsbl.bin");

        const fsbl_step = b.step("fsbl", "Build the first-stage boot loader (weir-fsbl.bin)");
        fsbl_step.dependOn(&finstall.step);
    }
}
